### ISSUE TITLE
[Question]  SWM181CBT6 have only 8k RAM?

### ISSUE THREAD

**Issue by cjacker** [Synwit-Co-Ltd/Synwit.SWM32_GCC#1]
I use Luat SWM181 devboard (tested with 2 boards), the MCU model is "SWM181CBT6".

According to datasheet, it's 16K RAM and 120K FLASH.

I use the 'swm181.ld' from this repo, and change the RAM SIZE to 16K and build a demo to blink 3 LEDs on Luat SWM181 devboard.

But no lucky, it not works at all. 

Switch it back to 8k, everything works as expected.

**My question is: Does SWM181CBT6 have only 8k RAM?**

**Comment by XIVN1987** [comment]
CSL\CMSIS\DeviceSupport\startup\arm\startup_SWM181.s
``` C
; Sram Switch Configuration
; 			Code Size	 	Sram Size
;	0		16k				16k				Cache使能，程序存储器240K
;	1		8k				24k				Cache使能，程序存储器240K
;	3		24k		  		8k

SRAM_SWITCH	  EQU    0;
```

change SRAM_SWITCH to 0.

**Comment by cjacker** [comment]
Thanks.

I grep  it and found:
```
SWM181_StdPeriph_Driver/CSL/CMSIS/DeviceSupport/startup/iar/startup_SWM181.s:SRAM_SWITCH      EQU    3;
SWM181_StdPeriph_Driver/CSL/CMSIS/DeviceSupport/startup/gcc/startup_SWM181.S:    .equ SRAM_SWITCH, 3
SWM181_StdPeriph_Driver/CSL/CMSIS/DeviceSupport/startup/arm/startup_SWM181.s:SRAM_SWITCH          EQU    0;
```

MDK startup file set default value to 0, but iar and gcc startup file set default value to 3.

I think it should also set iar and gcc default value to 0 by default.

**Comment by XIVN1987** [comment]
I will change the default value.
Thanks for your feedback.
